logging:
  #level:
    #com:
      #majiang:
        #user:
          #majianguser: info
  #设置日志的位置
 #file: Logs/springboot.log
  #path: E:/Logs/
  #pattern:
    #日志在文件中的格式
   # file: "%d{yyyy-MM-dd HH:MM:ss} [%thread] %-5level %logger{50} - %msg%n"
  说明

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    



#自定义
majiang:
  alipay:
    ALI_APPID: 2016101600702065
    #ALI_MERCHANT_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiKYGm3mu0wR1bG70V5trRHrfZxjSFL54SvNF36FON3rx6GUqmNUApiKkSIyC2+JrElTHvfY+fEF6tDkicq+PU9+b4IeU4AteoyXRr3n0+2j1mkZF46pmNYZ1U8gjymGpcbVky7N9G/hh5mgRiHa0YEtOP0s2P52Akkqgltijk4CHYENOKwxhgNAJaYf4/LRo+271cWWSG8urL/lXgHUy4E0ntdOydG4NYV+HhKkSPXXB2QbaUlaJFVdVIMoNODnYzgpZEblNAYPeB5ToQMQ0cffSYlXNZGNeQAGl7FoqfQj1RH7CYWC21QkGXYJJTDJZ/KeayPBCtaud3W3vo7aXXAgMBAAECggEAA7RBAufHvAxBOGiMzChGzUoPVwkg//3TdYgcnMmQxwfUdFGJk/xZZ9l4SzLEN4m8N0tVJaxPkImWMAvIetOuU5oKC5bynnHqLS/U2fXuFHZ1upcOpJ1vPnyBVIRm0evLWishQ3mHrB53vqdW/ErDPm6HqJxfF69oUc2Ly7i6fGfc6/BvUIB+c/hTzieWYWxd/1JZ/E616jjq1JjmL6zwQa/giJX5z1R0l+1Uy9TlJl8fBKwBz8sUAYQbg0zN2i6iDwWc20xtDLTAuHpPvCcSsoemvzFFfy+mswEMbgiQ9xUE+RHi2Pi6S2ZMdQrACoXcH4Sbi1ckM8sqQnQzRxKgmQKBgQDWlqRB3+IJBSB+UXT3XKAG0yO/jKh5qIqxx6hwzRrCwsvq8BONpo6fmtY7UVlKVrepLbCeStg60UZUUKc9ozOYsodsjAm2IsoQo4iFph7GnTkeDh/v6X2BlUjNi0SChxo6jk8b17Ha5wSTPH/Px6QzjllXpFY6yHcZ8A17bBj78wKBgQDBdNY1gS+PiG5cG3+pK51rtucjJkX/vklC2PIQEfZorOtUpmu8HExC7TsSRPeg6L17ZBhHsQxGAUtaFAxbjxGL/d+mviizfsGUvrhUOmSOY4F/sfV7Jjf/2ZWs2kYlkWdyEodnSd8NhnyjApoegCNcCSTa/bSpyQPeWkAyNFbbjQKBgQCiaLb+yHRpwUCbegkdojPXlnuK4Okt0prN/L+GSCWF3Cq7sGIMJk/xih20HViIA+PTHip7U0geE/+3lqdM5jUJz6zhQYekGuZ1+187T8QhLCNrlOMlD8GWjqbgMhRy+c+nG8fR2cjZVVlIGlTdrEqhXo5N36oHqWtC7UU28VRjcwKBgHKu06nmSo6ZP2sk9hoQfAL167Hfp5GDeaTCPUWfkGbfU6bb/XQHhoIKZoFfFzlxn5p9bRNa9r6tV8Evr1+7wZguyR3tDu3Rj+qg4V81OpVakdNkaPU3Y+0tTNiqkPkGaL+sEk798NfwyQRNr5WzOsL9vLaBvk8ElmGDORlKA8+lAoGABfedgMjn09fiLMRJwb5jYi4K9Pl9EiYoScwpuy2PqOi5oNcduEp8Ciho/L8xtym15zMIhU4W5VrDRKzgvmgLRe5Bn5kWe1XVJwkpanMeMtSv508f5J98YR0hO5q/9RI+osSvRLPuV2tE7lug5zdbFYSZo0rcPxcquDS80wzpHjA=
    ALI_MERCHANT_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDbVlbF1zCZG74r/T9BQFQ0lB7+IyRPP5DwBEthWGwXLAlae/w0nrJFUyG598xDFQ2tGRyoBN9hAdaHUTiGJr4oP6Xe9MoJbMXEvMMkRGYF7wbJGrAsa1+p0Z6EVg7n6c1wKZLS/PWiW8jo6t2kfxY5F/1V8yL6u0bLD0f99fD+NnTEGWQrTPIKwHUj1xzJx/msYUpojdWhLtWfUXzNnioYOnUxYVVoIDTPD8XG4YnVm+o0UeKPan9SLo5SE10/dWIBRatPtC3F1y5enMrVVFQPBWu+qX5BTGp/Dij3368py8I+dVxiTVrPnTQPssL3bT1FiP7M1aSe22ZRAYMAAx0nAgMBAAECggEAPFNV0FosMqAvwNeJU0AHKOLoV0uBDA7WpTz5Io/4QrNI60sYhbx0GZ8Qsp5V3slmlopGmGumqH6h61vKaRM0z8sZquW2v7rb9g1YupvZV55zRlKBy+XITOOrbohg1yY167hzenY6dOo7qtwWE80kZpWThtU1dLKXePf9+/ptyuza0FQeTjbl7Xo726JcLJVIUHXcfnWRX3s7TUZF1qO0TBqzDmGfDO11n+yl+fDMP1/9qQAkIMZZUs8Iwn8bl4oti3SY8ITfYjThLhtXJMmQgpt4DSbZRKpFrF/XpMezt7UU6LlBwNtRId/SMfCCMtje8Q3pSF3/hr7NB9joivxe0QKBgQD5qB5hS+FahdYF1jPTnodyNnvENlJtd91GmGPzmXEnhWIyyRfiqYR+RHLaHY+h+a6SfrPNHdS1osGakPa/w/DWDxsY36/6k9t9dj5adUa8PcEuqoeJbrxD/swHUWc2gkw1eSFConGAGM3OXUdsY+jIejnjnlAMEgPZi2oxMd5Q2QKBgQDg6QI7NZV8uluCon6hw9KwQPYdBa2OAqabOEX8zJbctmTG0OvY/qd+R6iVC9ToJ6bFGOGvkgRPbYyhPpe8QAbadmr9KuyGmvp+F2LPTYmFEVWVreBHLO0HqIA5eSVAdqFbdmcjrOXA7xEgG62eiQVRh8rcqIu0WRyiTs1iBqgd/wKBgB/arZWoguZz8Szpec9kiM+v1/bfH4FMK/WX+Bja2S87u53TPrLzAi7COQ1PfEYkf3u9ot9nEP7j92PrXzB0pcQKRWDVGbUVLIpDjg0orY/TKVT0+To14NukJRBB+LNhyKuB+xZvd5/qikfsavKPhOIfhkdeqcQAgHE/cps4S69xAoGAKQKTw5Qbs+iPMxzKFlkMm9LcjaIxaUmWc4spR9VOVOR1L8N8nc6hX+dVGAhWRBam1B2bWVY4rvr8v5IYPN034rHhBFTFWC3+Kuu8uqwavUbR4j8YPCI2/kR9TP2IC18WQQUv/VNTeYCeEMq7N8MoUxt9pAqfnrz4+aeAz7UDBqUCgYBneilwHxbGy/GU1ew5We8vWMUs4ryDIXDVg4QPxgESsDpTJ0O0wWuIlds9rIa8aqn2znu/P6HSR/HZsdxXglprBdgrELH8YOf5qvBCnG66czpND4NPFf6Q89MS1UjfSyI84QsW8/8IZ5miCmg3mS44k5kA10kQtzMy8ju2eB2AEQ==
    #ALI_ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtaONOn2royujmsdCxWKC30t4wubE0QEc+8KN08Sclh/GNzWi4+FOgUxDaF8Mhc7qamjXEwPsXz0VebPbIA7eQfuLxyjbkzt13hNpqnmUbGSkjiVYbu5DPI+NW7hwfj8Cq6C1TU872cFfO8+T0kg5JheBxB08ktytXn1uhIoIKKSr0OTbvy2WFokfmtXSoyI0tiE9RDgLd5B5iRvy0+iCusx37hqe15PvP0xwv7DCrpvGrZO0I0+41LWy6OK4V1hZ/PyOfCFm5N0Mr9tH4xMLk+azekda6f51hQV/f1lebAdLrWcZngj6pYYDVM97nwvx1UL93vtr84cOgjzmGOPW7wIDAQAB
    ALI_ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtugDnu6SOzKwXh7kf40pVJg6nbOJkQM9CoVpAt6cfIi07YG5ieAuEIEMVIZauEZLl4MR3GyD71Lkbk8jyW6J56/7RiVu5PzUTgVY8cD6E5s0GglZC/UNY7hiKxXL9AQPTxuOnmq1fZLZ6QDFKaBJg41mJi4C7eFalH3dkG4zNEKCNyRA/2M7p0b4+04ixDmKeXAzeuxW/I1xdBoUvtwrZgiY8YMrTl6W24Es4kqK6lFUKOucIjuJuCfTBwj3qPKWlfJTeNFexNKCeWytz4ekND/S2BCIL60WL8/Pirs+EVlKiluNLvD7eUuFCeCds+kOAFPkPOdKbo4bN675YlM7JQIDAQAB
    ALI_NOTIFY_URL: http://localhost:8080/user/alipayNotifyNotice
    ALI_RETURN_URL: http://localhost:8080/user/alipayReturnNotice
    #ALI_NOTIFY_URL:  http://localhost:8080/user/page/ali/notify_url.jsp
    #ALI_RETURN_URL: http://localhost:8080/user/page/ali/return_url.jsp
    ALI_SIGN_TYPE: RSA2
    ALI_CHARSET: utf-8
    ALI_GATEWAYURL: https://openapi.alipaydev.com/gateway.do
    #支付宝正式网关： https://openapi.alipay.com/gateway.do




   #应用公钥证书路径
    ALI_CERT_PATH: \src\main\resources\templates\CRT\appCertPublicKey_2016101600702065.crt


   # 支付宝公钥证书文件路径
    ALIPAY_CERT_PATH: \src\main\resources\templates\CRT\alipayCertPublicKey_RSA2.crt

   #支付宝CA根证书文件路径
    ALI_ROOT_PATH: \src\main\resources\templates\CRT\alipayRootCert.crt


    #https://blog.csdn.net/qq_21067307/article/details/100730808   公钥证书方式接入