logging:
  #level:
    #com:
      #majiang:
        #user:
          #majianguser: info
  #设置日志的位置
 #file: Logs/springboot.log
  #path: E:/Logs/
  #pattern:
    #日志在文件中的格式
   # file: "%d{yyyy-MM-dd HH:MM:ss} [%thread] %-5level %logger{50} - %msg%n"

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    



#自定义
majiang:
  alipay:
    ALI_APPID: 2016101600702065
    #ALI_MERCHANT_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiKYGm3mu0wR1bG70V5trRHrfZxjSFL54SvNF36FON3rx6GUqmNUApiKkSIyC2+JrElTHvfY+fEF6tDkicq+PU9+b4IeU4AteoyXRr3n0+2j1mkZF46pmNYZ1U8gjymGpcbVky7N9G/hh5mgRiHa0YEtOP0s2P52Akkqgltijk4CHYENOKwxhgNAJaYf4/LRo+271cWWSG8urL/lXgHUy4E0ntdOydG4NYV+HhKkSPXXB2QbaUlaJFVdVIMoNODnYzgpZEblNAYPeB5ToQMQ0cffSYlXNZGNeQAGl7FoqfQj1RH7CYWC21QkGXYJJTDJZ/KeayPBCtaud3W3vo7aXXAgMBAAECggEAA7RBAufHvAxBOGiMzChGzUoPVwkg//3TdYgcnMmQxwfUdFGJk/xZZ9l4SzLEN4m8N0tVJaxPkImWMAvIetOuU5oKC5bynnHqLS/U2fXuFHZ1upcOpJ1vPnyBVIRm0evLWishQ3mHrB53vqdW/ErDPm6HqJxfF69oUc2Ly7i6fGfc6/BvUIB+c/hTzieWYWxd/1JZ/E616jjq1JjmL6zwQa/giJX5z1R0l+1Uy9TlJl8fBKwBz8sUAYQbg0zN2i6iDwWc20xtDLTAuHpPvCcSsoemvzFFfy+mswEMbgiQ9xUE+RHi2Pi6S2ZMdQrACoXcH4Sbi1ckM8sqQnQzRxKgmQKBgQDWlqRB3+IJBSB+UXT3XKAG0yO/jKh5qIqxx6hwzRrCwsvq8BONpo6fmtY7UVlKVrepLbCeStg60UZUUKc9ozOYsodsjAm2IsoQo4iFph7GnTkeDh/v6X2BlUjNi0SChxo6jk8b17Ha5wSTPH/Px6QzjllXpFY6yHcZ8A17bBj78wKBgQDBdNY1gS+PiG5cG3+pK51rtucjJkX/vklC2PIQEfZorOtUpmu8HExC7TsSRPeg6L17ZBhHsQxGAUtaFAxbjxGL/d+mviizfsGUvrhUOmSOY4F/sfV7Jjf/2ZWs2kYlkWdyEodnSd8NhnyjApoegCNcCSTa/bSpyQPeWkAyNFbbjQKBgQCiaLb+yHRpwUCbegkdojPXlnuK4Okt0prN/L+GSCWF3Cq7sGIMJk/xih20HViIA+PTHip7U0geE/+3lqdM5jUJz6zhQYekGuZ1+187T8QhLCNrlOMlD8GWjqbgMhRy+c+nG8fR2cjZVVlIGlTdrEqhXo5N36oHqWtC7UU28VRjcwKBgHKu06nmSo6ZP2sk9hoQfAL167Hfp5GDeaTCPUWfkGbfU6bb/XQHhoIKZoFfFzlxn5p9bRNa9r6tV8Evr1+7wZguyR3tDu3Rj+qg4V81OpVakdNkaPU3Y+0tTNiqkPkGaL+sEk798NfwyQRNr5WzOsL9vLaBvk8ElmGDORlKA8+lAoGABfedgMjn09fiLMRJwb5jYi4K9Pl9EiYoScwpuy2PqOi5oNcduEp8Ciho/L8xtym15zMIhU4W5VrDRKzgvmgLRe5Bn5kWe1XVJwkpanMeMtSv508f5J98YR0hO5q/9RI+osSvRLPuV2tE7lug5zdbFYSZo0rcPxcquDS80wzpHjA=
    ALI_MERCHANT_PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC26AOe7pI7MrBeHuR/jSlUmDqds4mRAz0KhWkC3px8iLTtgbmJ4C4QgQxUhlq4RkuXgxHcbIPvUuRuTyPJbonnr/tGJW7k/NROBVjxwPoTmzQaCVkL9Q1juGIrFcv0BA9PG46earV9ktnpAMUpoEmDjWYmLgLt4VqUfd2QbjM0QoI3JED/YzunRvj7TiLEOYp5cDN67Fb8jXF0GhS+3CtmCJjxgytOXpbbgSziSorqUVQo65wiO4m4J9MHCPeo8paV8lN40V7E0oJ5bK3Ph6Q0P9LYEIgvrRYvz8+Kuz4RWUqKW40u8Pt5S4UJ4J2z6Q4AU+Q850pujhs3rvliUzslAgMBAAECggEACHFDIYXfiA356A5C+8Q3QSlZo0fTNLdSjPbFdxVxYaopt8DCIKQRXD+oowoki9bqzE6Hd4YmvNg1pQXQIA8THHeaAI3fxYAKCKPkjBwdLuR+DimaS5v/BzhOh7CU3mmFj2A1QAiq4eXyWvfnIdm9Ku5O5bo/9lztgmcg3/bGNEY9oyq+DVr/R5UxRjsrYMRltBMD1uOnTpZtThGs3aQZu/uqjpgWIMkURrRnU62q6iXNo/1x/+CiFYpQUzblwPwuSoMeeJej6CWm8QkNnltsivWnFYpoNL3AsCfd31cJjfcwcbkcIe4BdlaeGfvqkgBPrCAJ4A6iwC9qKqpqZ0yMjQKBgQDdgtOlQ93v6kRj2e6dqXnaz08wZCfcAY6a1HcI+PH6yLRXNELn/EqCnrwo6hVI8khzblUEXQYy+oHRdu+Qs42AxY9+u/P3ojpE4hyLNLrbnY9aux7V39toGqfDE+SlHmrjLUj0l8UyIWum+/f3J7BU9FDVShi6/n40/6zCQ6tLOwKBgQDTYnKGkTPUcsBUsUm4DlPUhcNAXibi4iMnJcYsEwOL69SB3YZGH8qzhpem9NLI92Grrz2mTI9NP28tsa2BCLISyxq6slyOgVSzKntTJYB1HOSYrbOELUtWwRLjp+4iC9VnXvjhnwed/AvWN7asTzb5KHixAM/YklKOc+BGCddtHwKBgQCoUimRg6i6DkI5vfjcRVQbOTzrgK/pNiWu8ZQidUkrUCf5u/S7Y7Ma3pQMYxQZgkIbtNNVpXp4cnMDQGV6h3YXTAhmPVx96ABvJ4KZJVB4YZn1UAt2aczHprmkOxGbhymhx1+QvWNTXKH5Ga6rWLVdWOmzqcJxFcHBdCdK1zDq0QKBgQCp5IkJkLBogqYEK82FKbbEq5GHLWTxmzEHqLuC9vE1xyAwFBx0Rd8DtRwz6rdzICiW9SyGeSf/vQkdX52EhLmikyzzeqEbQ+UQbwdZh12cQtGTyJ/sjv7rRhhpcrHZGUu2XkWICOn1Vvsoe/TMvon/bUC7elySwt+pcIaDpCtJnwKBgGSvWZGZ5zhBa1hz5VfyL6b+ww1nfm003FoxBJ6u1751CkgEuWu9hGMAwHLOzIeMQGv0C2tvp9u8UxzNBOigcuT6+7dqLYjUbzMOBAXjTN6cfYelvwCX0b5TF+iLlow7N2gSwyAbKwytRMf7qnJKkl54zXk0ggguI+9mRcEAtVkX
    #ALI_ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtaONOn2royujmsdCxWKC30t4wubE0QEc+8KN08Sclh/GNzWi4+FOgUxDaF8Mhc7qamjXEwPsXz0VebPbIA7eQfuLxyjbkzt13hNpqnmUbGSkjiVYbu5DPI+NW7hwfj8Cq6C1TU872cFfO8+T0kg5JheBxB08ktytXn1uhIoIKKSr0OTbvy2WFokfmtXSoyI0tiE9RDgLd5B5iRvy0+iCusx37hqe15PvP0xwv7DCrpvGrZO0I0+41LWy6OK4V1hZ/PyOfCFm5N0Mr9tH4xMLk+azekda6f51hQV/f1lebAdLrWcZngj6pYYDVM97nwvx1UL93vtr84cOgjzmGOPW7wIDAQAB
    ALI_ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtugDnu6SOzKwXh7kf40pVJg6nbOJkQM9CoVpAt6cfIi07YG5ieAuEIEMVIZauEZLl4MR3GyD71Lkbk8jyW6J56/7RiVu5PzUTgVY8cD6E5s0GglZC/UNY7hiKxXL9AQPTxuOnmq1fZLZ6QDFKaBJg41mJi4C7eFalH3dkG4zNEKCNyRA/2M7p0b4+04ixDmKeXAzeuxW/I1xdBoUvtwrZgiY8YMrTl6W24Es4kqK6lFUKOucIjuJuCfTBwj3qPKWlfJTeNFexNKCeWytz4ekND/S2BCIL60WL8/Pirs+EVlKiluNLvD7eUuFCeCds+kOAFPkPOdKbo4bN675YlM7JQIDAQAB
    ALI_NOTIFY_URL: http://localhost:8080/user/alipayNotifyNotice
    ALI_RETURN_URL: http://localhost:8080/user/alipayReturnNotice
    #ALI_NOTIFY_URL:  http://localhost:8080/user/page/ali/notify_url.jsp
    #ALI_RETURN_URL: http://localhost:8080/user/page/ali/return_url.jsp
    ALI_SIGN_TYPE: RSA2
    ALI_CHARSET: utf-8
    ALI_GATEWAYURL: https://openapi.alipaydev.com/gateway.do
    #支付宝正式网关： https://openapi.alipay.com/gateway.do




   #应用公钥证书路径
    ALI_CERT_PATH: \src\main\resources\templates\CRT\appCertPublicKey_2016101600702065.crt


   # 支付宝公钥证书文件路径
    ALIPAY_CERT_PATH: \src\main\resources\templates\CRT\alipayCertPublicKey_RSA2.crt

   #支付宝CA根证书文件路径
    ALI_ROOT_PATH: \src\main\resources\templates\CRT\alipayRootCert.crt


    #https://blog.csdn.net/qq_21067307/article/details/100730808   公钥证书方式接入