logging:
  #level:
    #com:
      #majiang:
        #user:
          #majianguser: info
  #设置日志的位置
 #file: Logs/springboot.log
  #path: E:/Logs/
  #pattern:
    #日志在文件中的格式
   # file: "%d{yyyy-MM-dd HH:MM:ss} [%thread] %-5level %logger{50} - %msg%n"

spring:
  thymeleaf:
    cache: false



#自定义
majiang:
  alipay:
    ALI_APPID: 2016101600702065
    ALI_MERCHANT_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBixvrY/wfu7q7URG+htY/gvWQe2Rt933+v6qeAI+rx9/i+wUUt+KXofk2Z/VJTVKee1zc/e4tvpzKBhfUtkld0BznB9Op0kSX86lu9Omo0HxKL9HuZu0ADK6pRRe8qT/9XAEvccAwm8mVtb0vCAIQKvMWKHEo5GuQVtCh00puz9PsXIzheoPG5XKGoZLPz3HTmgNLNcJEugrDJYGelM8tIiNpwqI8suoJ71NgOCaQCZH8Zz9i3aFDKdlVZCSrPX4XsdQwuH0swbpwcz9/EXiZp7G1gZdGwG/7m0RUiOQ2Z5oYhAKxbiyj9YMqaXeGl5h9WazdvR4RIzbVDjHzlFERAgMBAAECggEAQe5WAGC78j6ulCV3nXus0VhKuQVEIP/EfYJ5SL9KYAhzN2fAt0G7rqb+WqVgXrVe5lAs/EC1F00bKWsed+Fqx7di7ma6YIUm6htWUaWOwp+RkoRyGR8DYnIR9w62PQv7CGzqIYaIZXT0jSCZL7Woryfc3psotMJEyIqW1rXd/TVIXmDFcqNOxFDr5/62arAxbgDyuEnWWsh3t5yiWTzksEjtodtpvpr8vBLhJ0e5Kto/v2eSxjJES+uQ/cTj3iHtoKWbPYmJh48WnzWFKDEYrs30Aw0ovKnP0ucD8CA7naE/rSrXRnlHIRFletMI9bAB0N5LmFv7eG4aFweU5FmQvQKBgQDPTBzuU7D4NzPvyvHbcDGuG3yRuvuAdzpwJj7WYynPxMKMyxJOqDgJsLL3eqOSuXqrI8v/HD4mPhzI+RRqL4IflSyGhQWPTVWZe531ZJDnDh2yOMDxiOCSABh5eS21hWIcvc8ukhn4yKqsSlO7+2xGgvO2vCpjB2WfSCmnSkQTgwKBgQCf+n1/IwuMEhwNsJtKOV30HcZ67NKCTHud5a40QUuPuDY4fsSfTTBZccaXg9r8D3Mq1YLOBwUUHJtQMOr3TMkSJ4gbC5OvB21unhbO6A1r2pY30G6OoDyvWe4dAlQdnZrN/hKbLdaO2VDaNGAmslPPSfrItoxiewjjNak8yJfg2wKBgQClE6qSS4lJEMTGNynEoqKdUHwxnOI9GjUqK/qsRQl9z+VRs0Ef7Cu747+Q/lOWOygpcvc3b2k6kQnhLSEJsk2AEw4DDZkw1dfNwrg2O2B87yvMyg80CNk0yuiyi0JQJCjOVITRRD10dXAchZAKyZwexpeHtG5YsAJIBnJNKwHtOwKBgB9SzH+4POqQIS4NBlriIKNLsTEgbZdVol6oOhPBNSpOx08Igzctxem9fUTtbFMuMz6Pz6zHcxcdAswQx/Dj9/q2AtBI1AHRUnv2OEEK7pXPltoW1Y7XkQpEcXr8mbuywDzVIo9/yiLuKgaPesQY5pAPzCrAk3w02uih+SENpa9BAoGAMq7RdTOOcayR0Vj4B1Le+oR3b7fL0/ufh9yMHI/8xIDRN7GUo6YkfUCLOaDcsIzIGwq0KsY7RLZDN0hcsu+9WXI7TG5CqAdzbWtTtfIcLFee9Ky/wAQQwPh4uSDAmZgHV1nc3dl4VPPimWiwQKxl/Qo7f4EaxJiZC4tiG6lYMeY=
    ALI_ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtaONOn2royujmsdCxWKC30t4wubE0QEc+8KN08Sclh/GNzWi4+FOgUxDaF8Mhc7qamjXEwPsXz0VebPbIA7eQfuLxyjbkzt13hNpqnmUbGSkjiVYbu5DPI+NW7hwfj8Cq6C1TU872cFfO8+T0kg5JheBxB08ktytXn1uhIoIKKSr0OTbvy2WFokfmtXSoyI0tiE9RDgLd5B5iRvy0+iCusx37hqe15PvP0xwv7DCrpvGrZO0I0+41LWy6OK4V1hZ/PyOfCFm5N0Mr9tH4xMLk+azekda6f51hQV/f1lebAdLrWcZngj6pYYDVM97nwvx1UL93vtr84cOgjzmGOPW7wIDAQAB
    ALI_NOTIFY_URL: http://localhost:8080/user/page/alialipay.trade.page.pay-JAVA-UTF-8/notify_url.jsp
    ALI_RETURN_URL: http://localhost:8080/user/page/alipay.trade.page.pay-JAVA-UTF-8/return_url.jsp
    ALI_SIGN_TYPE: RSA2
    ALI_CHARSET: utf-8
    ALI_GATEWAYURL: https://openapi.alipaydev.com/gateway.do
    #支付宝正式网关： https://openapi.alipay.com/gateway.do