logging:
  #level:
    #com:
      #majiang:
        #user:
          #majianguser: info
  #设置日志的位置
 #file: Logs/springboot.log
  #path: E:/Logs/
  #pattern:
    #日志在文件中的格式
   # file: "%d{yyyy-MM-dd HH:MM:ss} [%thread] %-5level %logger{50} - %msg%n"

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/



#自定义
majiang:
  alipay:
    ALI_APPID: 2016101600702065
    ALI_MERCHANT_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiKYGm3mu0wR1bG70V5trRHrfZxjSFL54SvNF36FON3rx6GUqmNUApiKkSIyC2+JrElTHvfY+fEF6tDkicq+PU9+b4IeU4AteoyXRr3n0+2j1mkZF46pmNYZ1U8gjymGpcbVky7N9G/hh5mgRiHa0YEtOP0s2P52Akkqgltijk4CHYENOKwxhgNAJaYf4/LRo+271cWWSG8urL/lXgHUy4E0ntdOydG4NYV+HhKkSPXXB2QbaUlaJFVdVIMoNODnYzgpZEblNAYPeB5ToQMQ0cffSYlXNZGNeQAGl7FoqfQj1RH7CYWC21QkGXYJJTDJZ/KeayPBCtaud3W3vo7aXXAgMBAAECggEAA7RBAufHvAxBOGiMzChGzUoPVwkg//3TdYgcnMmQxwfUdFGJk/xZZ9l4SzLEN4m8N0tVJaxPkImWMAvIetOuU5oKC5bynnHqLS/U2fXuFHZ1upcOpJ1vPnyBVIRm0evLWishQ3mHrB53vqdW/ErDPm6HqJxfF69oUc2Ly7i6fGfc6/BvUIB+c/hTzieWYWxd/1JZ/E616jjq1JjmL6zwQa/giJX5z1R0l+1Uy9TlJl8fBKwBz8sUAYQbg0zN2i6iDwWc20xtDLTAuHpPvCcSsoemvzFFfy+mswEMbgiQ9xUE+RHi2Pi6S2ZMdQrACoXcH4Sbi1ckM8sqQnQzRxKgmQKBgQDWlqRB3+IJBSB+UXT3XKAG0yO/jKh5qIqxx6hwzRrCwsvq8BONpo6fmtY7UVlKVrepLbCeStg60UZUUKc9ozOYsodsjAm2IsoQo4iFph7GnTkeDh/v6X2BlUjNi0SChxo6jk8b17Ha5wSTPH/Px6QzjllXpFY6yHcZ8A17bBj78wKBgQDBdNY1gS+PiG5cG3+pK51rtucjJkX/vklC2PIQEfZorOtUpmu8HExC7TsSRPeg6L17ZBhHsQxGAUtaFAxbjxGL/d+mviizfsGUvrhUOmSOY4F/sfV7Jjf/2ZWs2kYlkWdyEodnSd8NhnyjApoegCNcCSTa/bSpyQPeWkAyNFbbjQKBgQCiaLb+yHRpwUCbegkdojPXlnuK4Okt0prN/L+GSCWF3Cq7sGIMJk/xih20HViIA+PTHip7U0geE/+3lqdM5jUJz6zhQYekGuZ1+187T8QhLCNrlOMlD8GWjqbgMhRy+c+nG8fR2cjZVVlIGlTdrEqhXo5N36oHqWtC7UU28VRjcwKBgHKu06nmSo6ZP2sk9hoQfAL167Hfp5GDeaTCPUWfkGbfU6bb/XQHhoIKZoFfFzlxn5p9bRNa9r6tV8Evr1+7wZguyR3tDu3Rj+qg4V81OpVakdNkaPU3Y+0tTNiqkPkGaL+sEk798NfwyQRNr5WzOsL9vLaBvk8ElmGDORlKA8+lAoGABfedgMjn09fiLMRJwb5jYi4K9Pl9EiYoScwpuy2PqOi5oNcduEp8Ciho/L8xtym15zMIhU4W5VrDRKzgvmgLRe5Bn5kWe1XVJwkpanMeMtSv508f5J98YR0hO5q/9RI+osSvRLPuV2tE7lug5zdbFYSZo0rcPxcquDS80wzpHjA=
    ALI_ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtaONOn2royujmsdCxWKC30t4wubE0QEc+8KN08Sclh/GNzWi4+FOgUxDaF8Mhc7qamjXEwPsXz0VebPbIA7eQfuLxyjbkzt13hNpqnmUbGSkjiVYbu5DPI+NW7hwfj8Cq6C1TU872cFfO8+T0kg5JheBxB08ktytXn1uhIoIKKSr0OTbvy2WFokfmtXSoyI0tiE9RDgLd5B5iRvy0+iCusx37hqe15PvP0xwv7DCrpvGrZO0I0+41LWy6OK4V1hZ/PyOfCFm5N0Mr9tH4xMLk+azekda6f51hQV/f1lebAdLrWcZngj6pYYDVM97nwvx1UL93vtr84cOgjzmGOPW7wIDAQAB
    ALI_NOTIFY_URL: http://localhost:8080/user/alipayNotifyNotice
    ALI_RETURN_URL: http://localhost:8080/user/alipayReturnNotice
    #ALI_NOTIFY_URL:  http://localhost:8080/user/page/ali/notify_url.jsp
    #ALI_RETURN_URL: http://localhost:8080/user/page/ali/return_url.jsp
    ALI_SIGN_TYPE: RSA2
    ALI_CHARSET: utf-8
    ALI_GATEWAYURL: https://openapi.alipaydev.com/gateway.do
    #支付宝正式网关： https://openapi.alipay.com/gateway.do